#pragma once

#define TERRAIN_SEMANTIC_MODELVIEWPROJECTION        "ModelViewProjection"
#define TERRAIN_SEMANTIC_INVVIEWPROJECTION			"InvViewProjection"
#define TERRAIN_SEMANTIC_MODEL                      "Model"
#define TERRAIN_SEMANTIC_VIEW                       "View"
#define TERRAIN_SEMANTIC_MODELVIEW                  "ModelView"  
#define TERRAIN_SEMANTIC_INVMODEL					"InvModel"  
#define TERRAIN_SEMANTIC_INVVIEW                    "InvView"
#define TERRAIN_SEMANTIC_INVMODELVIEW               "InvModelView"
#define TERRAIN_SEMANTIC_VIEWPROJECTION             "ViewProjection"
#define TERRAIN_SEMANTIC_PROJECTION                 "Projection"
#define TERRAIN_SEMANTIC_INVPROJECTION              "InvProjection"
#define TERRAIN_SEMANTIC_CAMERAPOSITION             "CameraPosition"
#define TERRAIN_SEMANTIC_SCREENSIZE					"ScreenSize"
#define TERRAIN_SEMANTIC_CAMERAPOSITION				"CameraPosition"
#define TERRAIN_SEMANTIC_TIMEANDRANDOM				"TimeAndRandom"
#define TERRAIN_SEMANTIC_LIGHTTILEWORKGROUPS		"LightTileWorkGroups"
#define TERRAIN_SEMANTIC_VIEWTOTEXTURESPACE			"ViewToTextureSpace"

#define TERRAIN_SEMANTIC_ALBEDOMAP					"AlbedoMap"
#define TERRAIN_SEMANTIC_NORMALMAP					"NormalMap"
#define TERRAIN_SEMANTIC_SPECULARMAP				"SpecularMap"
#define TERRAIN_SEMANTIC_ROUGHNESSMAP				"RoughnessMap"
#define TERRAIN_SEMANTIC_HEIGHTMAP					"heightmap"

#define TERRAIN_SEMANTIC_ALBEDOMAP_MULTI(x)			TERRAIN_SEMANTIC_ALBEDOMAP#x
#define TERRAIN_SEMANTIC_NORMALMAP_MULTI(x)			TERRAIN_SEMANTIC_NORMALMAP#x
#define TERRAIN_SEMANTIC_SPECULARMAP_MULTI(x)		TERRAIN_SEMANTIC_SPECULARMAP#x
#define TERRAIN_SEMANTIC_ROUGHNESSMAP_MULTI(x)		TERRAIN_SEMANTIC_ROUGHNESSMAP#x

#define TERRAIN_SEMANTIC_ALBEDOMAP_MULTI_STR(x)			TERRAIN_SEMANTIC_ALBEDOMAP##x
#define TERRAIN_SEMANTIC_NORMALMAP_MULTI_STR(x)			TERRAIN_SEMANTIC_NORMALMAP##x
#define TERRAIN_SEMANTIC_SPECULARMAP_MULTI_STR(x)		TERRAIN_SEMANTIC_SPECULARMAP##x
#define TERRAIN_SEMANTIC_ROUGHNESSMAP_MULTI_STR(x)		TERRAIN_SEMANTIC_ROUGHNESSMAP##x
